/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as NFTCollectionContractJson } from "../NFTCollection.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace NFTCollectionTypes {
  export type Fields = {
    nftTemplateId: HexString;
    timeZoneController: HexString;
    owner: Address;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    minter: Address;
    index: bigint;
    nft: HexString;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    royaltyAmount: {
      params: CallContractParams<{ tokenId: HexString; salePrice: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  NFTCollectionInstance,
  NFTCollectionTypes.Fields
> {
  encodeFields(fields: NFTCollectionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as NFTCollectionTypes.Fields;
  }

  eventIndex = { Mint: 0 };
  consts = {
    Price: BigInt(5000000000000000000),
    RoyaltyRate: BigInt(500),
    ErrorCodes: {
      NFTNotFound: BigInt(0),
      CollectionOwnerAllowedOnly: BigInt(1),
      NFTNotPartOfCollection: BigInt(2),
    },
  };

  at(address: string): NFTCollectionInstance {
    return new NFTCollectionInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<NFTCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<NFTCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params);
    },
    mint: async (
      params: Omit<
        TestContractParamsWithoutMaps<NFTCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "mint", params);
    },
    royaltyAmount: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { tokenId: HexString; salePrice: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "royaltyAmount", params);
    },
    payRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { payer_: Address; amount_: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "payRoyalty", params);
    },
    withdrawRoyalty: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { to_: Address; amount_: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawRoyalty", params);
    },
    withdrawAlph: async (
      params: TestContractParamsWithoutMaps<
        NFTCollectionTypes.Fields,
        { to_: Address; amount_: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdrawAlph", params);
    },
    destroyInfrastructure: async (
      params: Omit<
        TestContractParamsWithoutMaps<NFTCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroyInfrastructure", params);
    },
  };
}

// Use this object to test and deploy the contract
export const NFTCollection = new Factory(
  Contract.fromJson(
    NFTCollectionContractJson,
    "",
    "fad19cb20fec363fd60fb0f99e78f3429e8c4f9fa8a81a49628a9003d6d87f72",
    []
  )
);

// Use this class to interact with the blockchain
export class NFTCollectionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<NFTCollectionTypes.State> {
    return fetchContractState(NFTCollection, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<NFTCollectionTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      NFTCollection.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  methods = {
    getCollectionUri: async (
      params?: NFTCollectionTypes.CallMethodParams<"getCollectionUri">
    ): Promise<NFTCollectionTypes.CallMethodResult<"getCollectionUri">> => {
      return callMethod(
        NFTCollection,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: NFTCollectionTypes.CallMethodParams<"totalSupply">
    ): Promise<NFTCollectionTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        NFTCollection,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: NFTCollectionTypes.CallMethodParams<"nftByIndex">
    ): Promise<NFTCollectionTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        NFTCollection,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    royaltyAmount: async (
      params: NFTCollectionTypes.CallMethodParams<"royaltyAmount">
    ): Promise<NFTCollectionTypes.CallMethodResult<"royaltyAmount">> => {
      return callMethod(
        NFTCollection,
        this,
        "royaltyAmount",
        params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends NFTCollectionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<NFTCollectionTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      NFTCollection,
      this,
      calls,
      getContractByCodeHash
    )) as NFTCollectionTypes.MultiCallResults<Calls>;
  }
}
