/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TimeZoneControllerContractJson } from "../TimeZoneController.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace TimeZoneControllerTypes {
  export type Fields = {
    owner: Address;
    collection: Address;
    minted: bigint;
    offsetCoordinator: HexString;
    abbrCoordinator: HexString;
    zoneCoordinator: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getStuff: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, HexString, HexString]>;
    };
    setCollection: {
      params: CallContractParams<{ collection_: Address }>;
      result: CallContractResult<null>;
    };
    getItem: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint, HexString]>;
    };
    destroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    getStuff: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setCollection: {
      params: SignExecuteContractMethodParams<{ collection_: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getItem: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    destroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  TimeZoneControllerInstance,
  TimeZoneControllerTypes.Fields
> {
  encodeFields(fields: TimeZoneControllerTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as TimeZoneControllerTypes.Fields;
  }

  consts = {
    MAX_SUPPLY: BigInt(377),
    ErrorCode: { OutOfStock: BigInt(69), UnAuthorized: BigInt(420) },
  };

  at(address: string): TimeZoneControllerInstance {
    return new TimeZoneControllerInstance(address);
  }

  tests = {
    getStuff: async (
      params: Omit<
        TestContractParamsWithoutMaps<TimeZoneControllerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<
      TestContractResultWithoutMaps<[HexString, HexString, HexString]>
    > => {
      return testMethod(this, "getStuff", params, getContractByCodeHash);
    },
    setCollection: async (
      params: TestContractParamsWithoutMaps<
        TimeZoneControllerTypes.Fields,
        { collection_: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setCollection", params, getContractByCodeHash);
    },
    getItem: async (
      params: Omit<
        TestContractParamsWithoutMaps<TimeZoneControllerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<
      TestContractResultWithoutMaps<[HexString, bigint, HexString]>
    > => {
      return testMethod(this, "getItem", params, getContractByCodeHash);
    },
    getRandom: async (
      params: Omit<
        TestContractParamsWithoutMaps<TimeZoneControllerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getRandom", params, getContractByCodeHash);
    },
    destroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<TimeZoneControllerTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroy", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const TimeZoneController = new Factory(
  Contract.fromJson(
    TimeZoneControllerContractJson,
    "",
    "783a1b4487881b694bd9723ccdac97a90a2c9a3e3ae3b75929f919a2c0644f21",
    []
  )
);

// Use this class to interact with the blockchain
export class TimeZoneControllerInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TimeZoneControllerTypes.State> {
    return fetchContractState(TimeZoneController, this);
  }

  methods = {
    getStuff: async (
      params?: TimeZoneControllerTypes.CallMethodParams<"getStuff">
    ): Promise<TimeZoneControllerTypes.CallMethodResult<"getStuff">> => {
      return callMethod(
        TimeZoneController,
        this,
        "getStuff",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setCollection: async (
      params: TimeZoneControllerTypes.CallMethodParams<"setCollection">
    ): Promise<TimeZoneControllerTypes.CallMethodResult<"setCollection">> => {
      return callMethod(
        TimeZoneController,
        this,
        "setCollection",
        params,
        getContractByCodeHash
      );
    },
    getItem: async (
      params?: TimeZoneControllerTypes.CallMethodParams<"getItem">
    ): Promise<TimeZoneControllerTypes.CallMethodResult<"getItem">> => {
      return callMethod(
        TimeZoneController,
        this,
        "getItem",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    destroy: async (
      params?: TimeZoneControllerTypes.CallMethodParams<"destroy">
    ): Promise<TimeZoneControllerTypes.CallMethodResult<"destroy">> => {
      return callMethod(
        TimeZoneController,
        this,
        "destroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    getStuff: async (
      params: TimeZoneControllerTypes.SignExecuteMethodParams<"getStuff">
    ): Promise<TimeZoneControllerTypes.SignExecuteMethodResult<"getStuff">> => {
      return signExecuteMethod(TimeZoneController, this, "getStuff", params);
    },
    setCollection: async (
      params: TimeZoneControllerTypes.SignExecuteMethodParams<"setCollection">
    ): Promise<
      TimeZoneControllerTypes.SignExecuteMethodResult<"setCollection">
    > => {
      return signExecuteMethod(
        TimeZoneController,
        this,
        "setCollection",
        params
      );
    },
    getItem: async (
      params: TimeZoneControllerTypes.SignExecuteMethodParams<"getItem">
    ): Promise<TimeZoneControllerTypes.SignExecuteMethodResult<"getItem">> => {
      return signExecuteMethod(TimeZoneController, this, "getItem", params);
    },
    destroy: async (
      params: TimeZoneControllerTypes.SignExecuteMethodParams<"destroy">
    ): Promise<TimeZoneControllerTypes.SignExecuteMethodResult<"destroy">> => {
      return signExecuteMethod(TimeZoneController, this, "destroy", params);
    },
  };

  async multicall<Calls extends TimeZoneControllerTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TimeZoneControllerTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      TimeZoneController,
      this,
      calls,
      getContractByCodeHash
    )) as TimeZoneControllerTypes.MultiCallResults<Calls>;
  }
}
