/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, ContractFactory } from "@alephium/web3";
import {
  NFT,
  NFTCollection,
  TimeZoneController,
  TimeZoneCoordinatorByteVec,
  TimeZoneCoordinatorU256,
  TimeZoneSpliceByteVec,
  TimeZoneSpliceU256,
} from ".";

let contracts: ContractFactory<any>[] | undefined = undefined;
export function getContractByCodeHash(codeHash: string): Contract {
  if (contracts === undefined) {
    contracts = [
      NFT,
      NFTCollection,
      TimeZoneController,
      TimeZoneCoordinatorByteVec,
      TimeZoneCoordinatorU256,
      TimeZoneSpliceByteVec,
      TimeZoneSpliceU256,
    ];
  }
  const c = contracts.find(
    (c) =>
      c.contract.codeHash === codeHash || c.contract.codeHashDebug === codeHash
  );
  if (c === undefined) {
    throw new Error("Unknown code with code hash: " + codeHash);
  }
  return c.contract;
}
